version: '3.8'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guess
      - RABBITMQ_DEFAULT_PASS=guess
    ports:
      # RabbitMq instance
      - '5672:5672'
      # WEB INTERFACE
      - '15672:15672'
      